import { Product } from '../types';

export const INITIAL_PRODUCTS: Product[] = [
  { 
    id: 1, 
    name: "KOVR AIR MAX 1", 
    price: 189, 
    oldPrice: 220,
    rating: 4.8,
    reviews: 124,
    description: "La silueta icónica que definió una era, ahora con tecnología Flyknit ultra-ligera.",
    img: "https://res.cloudinary.com/dk1tkgjpj/image/upload/v1775102645/KOVR_AIR_MAX_1_wll8ax.png", 
    color: "#FF3A2D", 
    pantone: "PANTONE 18-1664",
    tag: "NUEVO",
    category: "HOMBRE"
  },
  { 
    id: 2, 
    name: "KOVR STREET PRO", 
    price: 159, 
    oldPrice: 190,
    rating: 4.9,
    reviews: 89,
    description: "Diseñadas para el asfalto. Tracción superior y amortiguación reactiva en cada paso.",
    img: "https://res.cloudinary.com/dk1tkgjpj/image/upload/v1775102645/KOVR_STREET_PROs_r7kfl8.png", 
    color: "#1E3A8A", 
    pantone: "PANTONE 19-4052",
    tag: "SALE",
    category: "MUJER"
  },
  { 
    id: 3, 
    name: "KOVR URBAN X", 
    price: 175, 
    oldPrice: 210,
    rating: 4.7,
    reviews: 210,
    description: "Minimalismo y potencia. El equilibrio perfecto entre estilo urbano y rendimiento técnico.",
    img: "https://res.cloudinary.com/dk1tkgjpj/image/upload/v1775102645/KOVR_URBAN_X_mh0vcl.png", 
    color: "#111827", 
    pantone: "PANTONE 19-0303",
    tag: "NUEVO",
    category: "HOMBRE"
  },
  { 
    id: 4, 
    name: "KOVR VOLT RUN", 
    price: 195, 
    oldPrice: 230,
    rating: 4.9,
    reviews: 67,
    description: "Energía pura. Amortiguación de última generación para corredores de alto rendimiento.",
    img: "https://res.cloudinary.com/dk1tkgjpj/image/upload/v1775102645/KOVR_VOLT_RUN_cejkt0.png", 
    color: "#D9F99D", 
    pantone: "PANTONE 13-0650",
    tag: "COLAB",
    category: "MUJER"
  },
  { 
    id: 5, 
    name: "KOVR NEON NIGHT", 
    price: 210, 
    oldPrice: 250,
    rating: 4.8,
    reviews: 45,
    description: "Estilo futurista con detalles reflectantes para destacar en la oscuridad urbana.",
    img: "https://res.cloudinary.com/dk1tkgjpj/image/upload/v1775102645/KOVR_NEON_NIGHT_xzzqxf.png", 
    color: "#A855F7", 
    pantone: "PANTONE 18-3838",
    tag: "LIMITED",
    category: "KIDS"
  },
  { 
    id: 6, 
    name: "KOVR DESERT STORM", 
    price: 165, 
    oldPrice: 200,
    rating: 4.6,
    reviews: 32,
    description: "Tonos tierra y materiales premium. La elegancia del desierto en tus pies.",
    img: "https://res.cloudinary.com/dk1tkgjpj/image/upload/v1775102645/KOVR_DESERT_STORM_xgczpv.png", 
    color: "#D4A373", 
    pantone: "PANTONE 16-1325",
    tag: "NUEVO",
    category: "HOMBRE"
  },
];

export const ALL_PRODUCTS: Product[] = [
  { 
    id: 1, 
    name: "KOVR AIR MAX 1", 
    price: 189, 
    oldPrice: 220,
    rating: 4.8,
    reviews: 124,
    description: "La silueta icónica que definió una era, ahora con tecnología Flyknit ultra-ligera.",
    img: "https://res.cloudinary.com/dk1tkgjpj/image/upload/v1775680480/1_g8afa0.webp", 
    color: "#FF3A2D", 
    pantone: "PANTONE 18-1664",
    tag: "NUEVO",
    category: "LIFESTYLE"
  },
  { 
    id: 2, 
    name: "KOVR STREET PRO", 
    price: 159, 
    oldPrice: 190,
    rating: 4.9,
    reviews: 89,
    description: "Diseñadas para el asfalto. Tracción superior y amortiguación reactiva en cada paso.",
    img: "https://res.cloudinary.com/dk1tkgjpj/image/upload/v1775680481/2_caciky.webp", 
    color: "#1E3A8A", 
    pantone: "PANTONE 19-4052",
    tag: "SALE",
    category: "TRAINING"
  },
  { 
    id: 3, 
    name: "KOVR URBAN X", 
    price: 175, 
    oldPrice: 210,
    rating: 4.7,
    reviews: 210,
    description: "Minimalismo y potencia. El equilibrio perfecto entre estilo urbano y rendimiento técnico.",
    img: "https://res.cloudinary.com/dk1tkgjpj/image/upload/v1775680481/3_dpmrbz.webp", 
    color: "#111827", 
    pantone: "PANTONE 19-0303",
    tag: "NUEVO",
    category: "LIFESTYLE"
  },
  { 
    id: 4, 
    name: "KOVR VOLT RUN", 
    price: 195, 
    oldPrice: 230,
    rating: 4.9,
    reviews: 67,
    description: "Energía pura. Amortiguación de última generación para corredores de alto rendimiento.",
    img: "https://res.cloudinary.com/dk1tkgjpj/image/upload/v1775680481/4_gjqyqn.webp", 
    color: "#D9F99D", 
    pantone: "PANTONE 13-0650",
    tag: "COLAB",
    category: "RUNNING"
  },
  { 
    id: 5, 
    name: "KOVR NEON NIGHT", 
    price: 210, 
    oldPrice: 250,
    rating: 4.8,
    reviews: 45,
    description: "Estilo futurista con detalles reflectantes para destacar en la oscuridad urbana.",
    img: "https://res.cloudinary.com/dk1tkgjpj/image/upload/v1775680481/5_rrwfi0.webp", 
    color: "#A855F7", 
    pantone: "PANTONE 18-3838",
    tag: "LIMITED",
    category: "LIFESTYLE"
  },
  { 
    id: 6, 
    name: "KOVR DESERT STORM", 
    price: 165, 
    oldPrice: 200,
    rating: 4.6,
    reviews: 32,
    description: "Tonos tierra y materiales premium. La elegancia del desierto en tus pies.",
    img: "https://res.cloudinary.com/dk1tkgjpj/image/upload/v1775680483/6_qfh9mo.webp", 
    color: "#D4A373", 
    pantone: "PANTONE 16-1325",
    tag: "NUEVO",
    category: "LIFESTYLE"
  },
  { 
    id: 7, 
    name: "KOVR RUN ELITE", 
    price: 199, 
    oldPrice: 240, 
    rating: 5.0, 
    reviews: 56, 
    img: "https://res.cloudinary.com/dk1tkgjpj/image/upload/v1775680483/7_scvxwd.webp", 
    tag: "ELITE", 
    category: "RUNNING", 
    description: "Elite running performance.", 
    color: "#FF3A2D" 
  },
  { 
    id: 8, 
    name: "KOVR CLASSIC 85", 
    price: 129, 
    oldPrice: 150, 
    rating: 4.6, 
    reviews: 342, 
    img: "https://res.cloudinary.com/dk1tkgjpj/image/upload/v1775680484/8_dsk3fs.webp", 
    tag: "CLÁSICO", 
    category: "LIFESTYLE", 
    description: "Classic style for everyday.", 
    color: "#1E3A8A" 
  },
  { 
    id: 9, 
    name: "KOVR BOLD Z", 
    price: 210, 
    oldPrice: 250, 
    rating: 4.9, 
    reviews: 45, 
    img: "https://res.cloudinary.com/dk1tkgjpj/image/upload/v1775680485/9_mqdzo0.webp", 
    tag: "NUEVO", 
    category: "JORDAN", 
    description: "Bold design, bold performance.", 
    color: "#111827" 
  },
  { 
    id: 10, 
    name: "KOVR LITE V2", 
    price: 145, 
    oldPrice: 170, 
    rating: 4.5, 
    reviews: 112, 
    img: "https://res.cloudinary.com/dk1tkgjpj/image/upload/v1775680486/10_ediiyy.webp", 
    tag: "SALE", 
    category: "TRAINING", 
    description: "Lightweight and breathable.", 
    color: "#D9F99D" 
  },
  { 
    id: 11, 
    name: "KOVR TECH FLOW", 
    price: 230, 
    oldPrice: 280, 
    rating: 4.8, 
    reviews: 78, 
    img: "https://res.cloudinary.com/dk1tkgjpj/image/upload/v1775680486/11_eumqwo.webp", 
    tag: "COLAB", 
    category: "JORDAN", 
    description: "Technical flow for urban explorers.", 
    color: "#A855F7" 
  },
  { 
    id: 12, 
    name: "KOVR ZENITH", 
    price: 260, 
    oldPrice: 310, 
    rating: 5.0, 
    reviews: 24, 
    img: "https://res.cloudinary.com/dk1tkgjpj/image/upload/v1775680487/12_znrol9.webp", 
    tag: "PREMIUM", 
    category: "JORDAN", 
    description: "La cumbre del calzado urbano. Una pieza de ingeniería y diseño para los que no aceptan menos que la perfección.", 
    color: "#F8FAFC" 
  },
];
